### ISSUE TITLE
(.text+0x20): undefined reference to `main'

### ISSUE THREAD

**Issue by parthsarthiprasad** [isrivastav99/DSA#1]
https://github.com/isrivastav99/DSA/blob/master/Trees/diagonaltraversal.cpp buggy code.
:)

**Comment by isrivastav99** [comment]
> https://github.com/isrivastav99/DSA/blob/master/Trees/diagonaltraversal.cpp buggy code.
> :)

Thats an empty file that was pushed on the repo by mistake )
